//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTruyen_Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts()
        {
            this.Comments = new HashSet<Comments>();
            this.Chapters = new HashSet<Chapters>();
            this.Interested = new HashSet<Interested>();
        }
    
        public System.Guid IdPost { get; set; }
        public string PostName { get; set; }
        public string NameAscii { get; set; }
        public string Introduction { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Note { get; set; }
        public System.Guid IdUser { get; set; }
        public string Source { get; set; }
        public string Author { get; set; }
        public bool IsDelete { get; set; }
        public bool IsFull { get; set; }
        public int IdCategory { get; set; }
        public string Type { get; set; }
        public string Child { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapters> Chapters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interested> Interested { get; set; }
        public virtual Users Users { get; set; }
    }
}
